require('dotenv').config();
const express=require('express'),session=require('express-session'),Database=require('better-sqlite3'),crypto=require('crypto'),path=require('path');
const app=express(),PORT=process.env.PORT||3000,db=new Database(process.env.DB_FILE||path.join(__dirname,'chess-masteries.db'));
app.use(express.json({limit:'5mb'}));app.use(session({secret:process.env.SESSION_SECRET||'chess-masteries-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production'}}));
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,chess_username TEXT DEFAULT '',contact TEXT DEFAULT '',role TEXT DEFAULT 'customer',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS courses(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT DEFAULT '',price_cents INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS chapters(id INTEGER PRIMARY KEY AUTOINCREMENT,course_id INTEGER,chapter_number INTEGER,title TEXT,pgn TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS purchases(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,course_id INTEGER,status TEXT DEFAULT 'pending',paypal_order_id TEXT UNIQUE,amount_cents INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
const email=v=>String(v||'').trim().toLowerCase(),hash=p=>{const s=crypto.randomBytes(16);return s.toString('hex')+':'+crypto.scryptSync(String(p),s,64).toString('hex')},verify=(p,x)=>{try{const[a,b]=String(x).split(':');return crypto.timingSafeEqual(crypto.scryptSync(String(p),Buffer.from(a,'hex'),64),Buffer.from(b,'hex'))}catch{return false}},pub=u=>u&&({id:u.id,name:u.name,email:u.email,chess_username:u.chess_username,contact:u.contact,role:u.role});
const current=req=>req.session.userId?db.prepare('SELECT * FROM users WHERE id=?').get(req.session.userId):null,auth=(req,res,next)=>current(req)?next():res.status(401).json({error:'Please log in first.'}),admin=(req,res,next)=>{const u=current(req);return u?.role==='admin'?next():res.status(403).json({error:'Admin only.'})};
function tokens(p){return String(p||'').replace(/\[[^\]]*\]/g,' ').replace(/\{[^}]*\}/gs,' ').replace(/;[^\n]*/g,' ').replace(/\([^()]*\)/g,' ').replace(/\$\d+/g,' ').replace(/\b(1-0|0-1|1\/2-1\/2|\*)\b/g,' ').split(/\s+/).filter(Boolean).filter(x=>!/^\d+\.(\.\.)?$/.test(x))}
function splitPgn(p){const t=tokens(p),a=[];for(let i=0,n=1;i<t.length;i+=40,n++)a.push({n,pgn:t.slice(i,i+40).join(' ')});return a}
app.get('/api/me',(q,s)=>s.json({user:pub(current(q))}));
app.post('/api/auth/register',(q,s)=>{const{name,email:e,password,chess_username='',contact=''}=q.body||{};if(!String(name||'').trim()||!e||String(password||'').length<8)return s.status(400).json({error:'Name, email and password (8+ characters) are required.'});try{const role=db.prepare('SELECT id FROM users LIMIT 1').get()?'customer':'admin',id=db.prepare('INSERT INTO users(name,email,password_hash,chess_username,contact,role) VALUES(?,?,?,?,?,?)').run(String(name).trim(),email(e),hash(password),String(chess_username).trim(),String(contact).trim(),role).lastInsertRowid;q.session.userId=id;s.json({user:pub(current(q))})}catch{s.status(400).json({error:'This email is already registered.'})}});
app.post('/api/auth/login',(q,s)=>{const u=db.prepare('SELECT * FROM users WHERE email=?').get(email(q.body?.email));if(!u||!verify(q.body?.password,u.password_hash))return s.status(401).json({error:'Invalid email or password.'});q.session.userId=u.id;s.json({user:pub(u)})});
app.post('/api/auth/logout',(q,s)=>q.session.destroy(()=>s.json({ok:true})));
app.put('/api/profile',auth,(q,s)=>{const u=current(q),{name,chess_username='',contact=''}=q.body||{};if(!String(name||'').trim())return s.status(400).json({error:'Name is required.'});db.prepare('UPDATE users SET name=?,chess_username=?,contact=? WHERE id=?').run(String(name).trim(),String(chess_username).trim(),String(contact).trim(),u.id);s.json({user:pub(current(q))})});
app.get('/api/courses',(q,s)=>s.json(db.prepare('SELECT c.*,COUNT(ch.id) chapter_count FROM courses c LEFT JOIN chapters ch ON ch.course_id=c.id GROUP BY c.id ORDER BY c.id DESC').all()));
app.get('/api/courses/:id',(q,s)=>{const c=db.prepare('SELECT * FROM courses WHERE id=?').get(q.params.id);if(!c)return s.status(404).json({error:'Course not found.'});const u=current(q),paid=!!(u&&db.prepare("SELECT id FROM purchases WHERE user_id=? AND course_id=? AND status='completed'").get(u.id,c.id));const chapters=db.prepare('SELECT id,chapter_number,title,pgn FROM chapters WHERE course_id=? ORDER BY chapter_number').all(c.id).map(x=>({...x,locked:!(u?.role==='admin'||paid||x.chapter_number===1),pgn:(u?.role==='admin'||paid||x.chapter_number===1)?x.pgn:null}));s.json({...c,purchased:paid,chapters})});
app.post('/api/admin/courses',admin,(q,s)=>{const{title,description='',price_cents=0,pgn=''}=q.body||{},parts=splitPgn(pgn);if(!String(title||'').trim()||!parts.length)return s.status(400).json({error:'Course title and valid PGN are required.'});const id=db.prepare('INSERT INTO courses(title,description,price_cents) VALUES(?,?,?)').run(String(title).trim(),String(description).trim(),Math.max(0,Math.round(Number(price_cents)*100))).lastInsertRowid,ins=db.prepare('INSERT INTO chapters(course_id,chapter_number,title,pgn) VALUES(?,?,?,?)');const tx=db.transaction(()=>parts.forEach(x=>ins.run(id,x.n,'Chapter '+x.n,x.pgn)));tx();s.json({ok:true,id,chapters:parts.length})});
app.delete('/api/admin/courses/:id',admin,(q,s)=>{db.prepare('DELETE FROM chapters WHERE course_id=?').run(q.params.id);db.prepare('DELETE FROM courses WHERE id=?').run(q.params.id);s.json({ok:true})});
app.get('/api/admin/users',admin,(q,s)=>s.json({users:db.prepare('SELECT id,name,email,chess_username,contact,role,created_at FROM users ORDER BY id DESC').all(),purchases:db.prepare('SELECT p.*,c.title FROM purchases p LEFT JOIN courses c ON c.id=p.course_id ORDER BY p.id DESC').all()}));
app.post('/api/admin/users/:id/role',admin,(q,s)=>{const role=q.body?.role==='admin'?'admin':'customer';db.prepare('UPDATE users SET role=? WHERE id=?').run(role,q.params.id);s.json({ok:true})});
app.use(express.static(path.join(__dirname,'public')));app.get('*',(q,s)=>s.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log('Chess Masteries running on port '+PORT));